<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Fluxor.Blazor.Web" Version="6.9.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.3"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.3" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.7" />
        <PackageReference Include="MudBlazor" Version="9.4.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Store\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\LegalDoc.Application\LegalDoc.Application.csproj" />
    </ItemGroup>

</Project>
