name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-analyze:
    name: Build, SonarCloud Scan & Docker Push
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: 🛒 Checkout code
        # actions/checkout@v4.1.7
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0

      - name: ⚙️ Setup .NET
        # actions/setup-dotnet@v4.0.1
        uses: actions/setup-dotnet@6bd20fd0e76814041d62c954e7d956a81b37349b
        with:
          dotnet-version: 8.x

      - name: ⚙️ Setup Java (Necesar pentru SonarScanner)
        # actions/setup-java@v4.2.1
        uses: actions/setup-java@99152e26f516060c14f923c19830528296ccd153
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🛠️ Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner

      # --- 1. SCANARE SONARCLOUD ---
      - name: 🧹 SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        run: |
          dotnet-sonarscanner begin /k:"robivagner_LegalDoc" /o:"robivagner" \
            /d:sonar.token="$SONAR_TOKEN" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.python.version=3.11 \
            /d:sonar.exclusions="**/bin/**,**/obj/**"
          
          dotnet build LegalDoc.sln
          
          dotnet-sonarscanner end /d:sonar.token="$SONAR_TOKEN"

      # --- 2. LOGIN LA GITHUB CONTAINER REGISTRY ---
      - name: 🐳 Login to GHCR
        # docker/login-action@v3.0.0
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- 3. BUILD & PUSH DOCKER IMAGES ---
      - name: 🚀 Build and Push Backend
        # docker/build-push-action@v5.3.0
        uses: docker/build-push-action@ca0523d759a41b592473079b6d3735c5b750165a
        with:
          context: ./Backend
          push: true
          tags: ghcr.io/robivagner/legaldoc-api:latest

      - name: 🚀 Build and Push Frontend
        uses: docker/build-push-action@ca0523d759a41b592473079b6d3735c5b750165a
        with:
          context: ./Frontend
          push: true
          tags: ghcr.io/robivagner/legaldoc-web:latest

      - name: 🚀 Build and Push AI Service
        uses: docker/build-push-action@ca0523d759a41b592473079b6d3735c5b750165a
        with:
          context: ./Python
          push: true
          tags: ghcr.io/robivagner/legaldoc-ai:latest